# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='likes',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='body',
        ),
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
