# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
