# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20160427_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=b'testauthor', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='added_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default='testuser', on_delete=django.db.models.deletion.CASCADE, to='ask.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='usertest', on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='added_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(to='ask.Like'),
        ),
    ]
